version: "3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user # データベースのユーザー名
      POSTGRES_PASSWORD: pass # データベースのパスワード
      POSTGRES_DB: db # 初期に作成するデータベース名
    ports:
      - "15432:5432" # localhost:15432をpostgresコンテナの5432にマッピング
    volumes:
      - pgdata:/var/lib/postgresql/data
  testdb:
    image: postgres:13
    environment:
      POSTGRES_USER: testuser # データベースのユーザー名
      POSTGRES_PASSWORD: testpass # データベースのパスワード
      POSTGRES_DB: testdb # 初期に作成するデータベース名
    ports:
      - "25432:5432" # localhost:25432をtestdbコンテナの5432にマッピング

volumes:
  pgdata: 